---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./stakater.yaml
  - ./hajimari.yaml
  - ./nfs-subdir-external.yaml
  - ./k8s-at-home.yaml
  - ./stiforr.yaml
  - ./bitnami.yaml
