apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:4vfQyFB/s3j9HhmYg/y61cxC2mEgP3OaPL3j15C8Ze3lIgh+UEYyTA==,iv:P5Sa+GVgMXzPapUaPw9bWiMfuePnqREzApJIS/wMWl8=,tag:TeSy+594uE+0dOna02pBdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165l3ul7sqdhgnc9arpjxlh09qmlux2rwljztmgvll5lhglclksps5e6t2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcklwUngxMGlJRjNBQ3gx
            SDZLbHRpNkdTcEJuMjBZajJBbkQ1VWQxVTBBCkkyUVo0RHFWekpFWWdVdXNxYXlS
            NE8yaGdBMmI1ZlN6dzN4TUpXaEgxK0kKLS0tIDVhQjV1RXZHOG1mSXNHdDJLN3Iz
            ZkpoZEJMUHpBeEw2R0V0R3VTVG1SbDgK8r18MzncAkIYVOA7aVxp8FnRW9GLGVN8
            sDCdIoOLPtsmN/VQ5uU8/8WSfl2mdfzqHl1FqzK0zww3lKZEyKVPaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T01:27:08Z"
    mac: ENC[AES256_GCM,data:/XW17Nt/lP0ZLkuNPTTVl+KRIEHGroHANKvM8OC0KWTE8oVg8LCj+vhaj4UGDbQ+yS3/F9PcxPK75xcITh6emdhrmxiRNze1Q7niyqIJ1Me0ugHTHJCzqZaJLe1H2Yo2yCOl3uvZVTyLmDFhmOfMVwQmJCVjxkdgyFBqjH4cjc0=,iv:nLzJZ2PaZqooAap0RtQZF/p7D5oNyq16QfMCDVW7ywY=,tag:2ur77xzYKSySsyr1mknP8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
