apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:cMkDJa79TZ2jACLecyIj9YbjlcjaFF0DldhNbI8cOqwUYtFyfnKuIA==,iv:64JvQxMJ1AnoG++Zg5D7VaPh+Xi3AhNPpg3Llk/O1I4=,tag:czx2IX8+urNTfpu/aKybLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165l3ul7sqdhgnc9arpjxlh09qmlux2rwljztmgvll5lhglclksps5e6t2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TkJHZmwvSFI1NU5scE1p
            czZoMEIraEZYN1ZhUXJZdENqaFNXYUdhOHhvCm9ldFA4R2NYbGcrSFRPdmNYKzli
            K2xnMWFjSUMrd0Fhb0txeWRQVEVsakEKLS0tIENtcHJ5TG5ZTUFieWYveUQ5Tm9I
            MDBaVitNUmQ2ZW56YlhHdlptWlk4cXMKVyq54UJPYpaFZwwfU0CIC/IZgLR89Sw/
            388sZz5ZLbw2sH6u+uxMdqJXglXQ62vNllmGVDvLRWPXLLv1wZt7RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T01:37:06Z"
    mac: ENC[AES256_GCM,data:sAGWksZ0IQWvrozIXoVyQchBhi11YPwHuzTWFpJXm2g28FFuatF/YedGWgHcgA7JNMtoqiMMGJQVOG6sIhj5p1TltmRv7/hz2si32aZJ0hdSEMC7R/Utn4b9mhHiMJ+14hBXESTgTak9QHYQTKcIvCYsCZcQzkKK05U6GjRAZlM=,iv:kn+2oqhzaZWt6ZcsNx6Ju1UG9Uj4mSSF1lvVEc4uT6E=,tag:FVineJ9t2NuORtBUwel5cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
