apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:+TIZxL/fQAcNQKXkMaANsfdbQVXZ3FfHFaUBXn5hDUNvIXLsQxUcSQ==,iv:RZ+M6JMZ1Ai0/glccBHtBFKP4eQCEabBWf2Zo0acdM4=,tag:/s9bq1fKbkcxguTZ2V9QJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165l3ul7sqdhgnc9arpjxlh09qmlux2rwljztmgvll5lhglclksps5e6t2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUVIzQndNTWd0ZzJDYXJx
            cU94cFNQV1NMdjRqamxZL203akEzRmRUWGtZClFhQ2Y0NkVlWkJFQmNUd2N5V2JW
            R3M1cXI5cWdOUVBjbHFpL2drSlA1bncKLS0tIHg2bVZwd0dmSGhGalBKbE5xejV5
            OEJxTllmdTBVeWdxeTd4eUJKZUFmaG8K3E07A4wKYo88pblH8KUK90lladaGb/dH
            m26nuvHrfi/PGXdgV3g4ulAH/ITIoPNgp3JFalKsjsIxO3UJRGxpCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T02:02:02Z"
    mac: ENC[AES256_GCM,data:mbD0taH9JqLNCb9oxb56OPLPGjQdf6oaqo+qcKCS6jgSU2pJ7h1dJadXuA4EKT/wMa8snyRQtZWJc0GgeQgzh+leDzjfk5qaB1WK3JnHy/a99JOSUJcnXQYI/OZ176PgBrUbqkanlofGroyjSuXqmNCM0CI88du9xGgXI6jRRBs=,iv:tFvEH/fdAejc9HPR+hPdq4+7Kwp2uKS5gJkqtnoK6Os=,tag:UPd0tdj/jr43MxhLIw2oUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
