apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:GXos8A14QqMHaKwQ/ZNaLSf4FZ86wjQ+SNZW5y3mcFik7s0xQ5HO7CD7spAlO2C49VhRoyRwRXafkiJMO0c/3fKDTlhvDocvDkcNDD8fOKAv+9iUjn9r5J+B7cKklA==,iv:MJQ9c6wVOyNW4tDusdwH76P9fOYI0GrPqrNuiHfSsp0=,tag:I6XaSUmgftn5lnarEjxlqQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZsRX9fS+oDmEESY=,iv:np1/q/nti+hh4jqdAqcPltsxjnd+UDW5qE4d8rJoa2Y=,tag:rmcskeLP0BWiVhkG4ySkQQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:fxF1qDxFz6h4V95glI2ahVdJTb5Y9w==,iv:g854Bli5GLcBw22xcH5TS8STRKkCsiYLbgCs6MES9Ig=,tag:PgAQnEquI4b4QXNlVZu9uA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:OTgJnhhN8JDpPe9o4bOGmhkq/z4T5Ui2ijod2JxezZq1SYh/,iv:hr7jdC8bFqSK3KeCVZEHi0+BXCMh+q3AYfyOWAi2Dl8=,tag:KCJfU645mXnTpLcuVka7Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165l3ul7sqdhgnc9arpjxlh09qmlux2rwljztmgvll5lhglclksps5e6t2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUEgxQ0pmdXBrMFBjd01Y
            YmlYdnFhdDg3aFRNd2JGQVRuTG9oYWM1NEVrCmpRc3BnclU3c0p2R0VxNkpreFB4
            S25sQ0djRVVrS28rV1d1Q3U3cVZlZjQKLS0tIGFjN2dkemxCaHZaQzV6eEhrczUr
            cWYxVmoxeUQwYTBlbWRyTFJXWGhVVGMKwvrlNqvxKc1cCRDaIT2BMUQIqFri/wnw
            5a26KNPwEnxXuR/A3ZBs0sOKxHVmH7tU6P6qzysZkGjjHofJlSqf8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T23:58:04Z"
    mac: ENC[AES256_GCM,data:uWg0jqjeY8HqxSdnzS6UmMd7xK0MAwwpRUpWnd+tbbFMygp/j9C8UkP3M9Jy/dmZuLtONhVlQsPdaQ1dpnR2IcbsOdRaV/sUKxI365JFEB8VKXwyQ5qLaFWQzACg7CGZ5v6dNvxcFUh9BNbNb646ujbjTPb19rAENcHRAzhrAKA=,iv:qBdoF9COOHwqPI0i6DYNFqG/vfgoTgdRa5qGNNEIaB8=,tag:Q3v9waOgxNAHY6sy+42rOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
