apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:qdFkNyEhqk1lHeBuGII5Fmtd0xFZZ93f0xtL6Eu/JiHlkMWbt331AQ==,iv:zZPClw7mwhtYMSwexL6FZciTb0gqh1hEclqcWXILoOM=,tag:35W3IWf0VpC8J6N9FIbUYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165l3ul7sqdhgnc9arpjxlh09qmlux2rwljztmgvll5lhglclksps5e6t2w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK2hnaXlqM0xSazJscE9P
            VU83WXZGS2NNMlZoQ2F1ZXd2TDBUNTVXazFBClB2ck1ZaHYwTVlpbFQxb2xkQ1BX
            TXNDUFUwMW40UHJZL1JSOFhEQ05SZ0kKLS0tIFN2ZDNMZjVVS3VOODZWaWowem5H
            U1FmcmZlb3NpQm5kTXRPZWgvdjJsamsKeqIMrZD9gs9ziwjsWZWBUz4ZSehMt4/w
            feVeZ9rUIeaInz5pi9BP66wCOmk3YLFek0IGQ+Z6rNHhtM8UjdS5ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T00:24:01Z"
    mac: ENC[AES256_GCM,data:oPVFsTBxOTUfpXj5C+0hgX1PTnCSYeYQr/FkTrzLRP8q1tpkgVF+zNHyeINcHb7eZtKm+r9yV3I8RPH4/NdQfEI01qlTxzML4BwP7YPyLOg7lFuPdLHLXNj1FWslV9g5o/P2vnTO8sRwXJY8KIomTd7I/7hrys9qPTOFC3yJpBc=,iv:uQwGPU12e2rGab0eK1MAM/EXTZmP3IWoZrLyP7uB1go=,tag:RZc1kqvtIWZJs+BywPFt0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
